[tools]
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:playwright" = "latest"
ruby = "4"
uv = "latest"

[settings]

[settings.python]
uv_venv_auto = "source"

[settings.ruby]
compile = true
